#pragma once

#define GRID_WIDTH 41
#define GRID_HEIGHT 26
#define CELL_SIZE 20

#define GROUND_HEIGHT (GRID_HEIGHT - 4) * CELL_SIZE

#define GRAVITY 300

#define SCREEN_WIDTH GRID_WIDTH * CELL_SIZE
#define SCREEN_HEIGHT GRID_HEIGHT * CELL_SIZE